language: python
python:
  # - "2.6" # Won't support until given reason to. See https://github.com/PeteHaitch/comethylation/issues/75.
  - "2.7"
  - "3.2"
  - "3.3"
  # - "3.4" # Currently failing due to problems installing Pysam v0.7.8 in Python 3.4 see https://github.com/PeteHaitch/comethylation/issues/75

install:
    - python setup.py install
script:
    - python setup.py test
