# From https://github.com/broadinstitute/viral-ngs/blob/master/.travis.yml
language: python
sudo: false

cache:
 directories:
  - $HOME/virtualenv
  - $HOME/miniconda

env:
  global:
  - CACHE_DIR="$HOME/virtualenv"
  - MINICONDA_DIR="$HOME/miniconda"

python:
  - 2.7
  - 3.4
  - 3.5

# # Container pkgs for building diamond.
# # These versioned and sources hacks should be removed once travis upgrades to
# # Ubuntu 14.04.
# addons:
#   apt:
#     sources:
#     - boost-latest # For newer boost
#     - ubuntu-toolchain-r-test # For newer gcc
#     packages:
#     - cmake
#     - gcc-4.9
#     - g++-4.9
#     - libboost1.55-all-dev

# before_install:
#   - travis/before_install.sh

install:
  - travis/install-conda.sh
  - export PATH="$PATH:$HOME/miniconda/bin"
  - hash -r
  - travis/install-pip.sh
  - travis/install-tools.sh

before_script:
  - flake8 --exit-zero .

script:
  - travis/tests-unit.sh
  - travis/tests-long.sh

after_success:
  - coveralls